AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for Oscar winner predictions
Resources:
  facebookNewsBotUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: bestFilm
          AttributeType: S
        - AttributeName: bestDirector
          AttributeType: S
        - AttributeName: bestActor
          AttributeType: S
        - AttributeName: bestActress
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: film-ID-index
          KeySchema:
            - AttributeName: bestFilm
              KeyType: HASH
            - AttributeName: ID
              KeyType: RANGE
        - IndexName: director-ID-index
          KeySchema:
            - AttributeName: bestDirector
              KeyType: HASH
            - AttributeName: ID
              KeyType: RANGE
        - IndexName: actor-ID-index
          KeySchema:
            - AttributeName: bestActor
              KeyType: HASH
            - AttributeName: ID
              KeyType: RANGE
        - IndexName: actress-ID-index
          KeySchema:
            - AttributeName: bestActress
              KeyType: HASH
            - AttributeName: ID
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: '2'
            WriteCapacityUnits: '1'
      ProvisionedThroughput:
        ReadCapacityUnits: '2'
        WriteCapacityUnits: '1'
