AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for football transfers
Resources:
  facebookNewsBotUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: team
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
        - AttributeName: team
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: team-ID-index
          KeySchema:
            - AttributeName: team
              KeyType: HASH
            - AttributeName: ID
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: '2'
            WriteCapacityUnits: '1'
      ProvisionedThroughput:
        ReadCapacityUnits: '2'
        WriteCapacityUnits: '1'
