AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Tables Template
Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
    Default: CODE
Resources:
  facebookNewsBotUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: notificationTimeUTC
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: notificationTimeUTC-ID-index
          KeySchema:
            - AttributeName: notificationTimeUTC
              KeyType: HASH
            - AttributeName: ID
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: '5'
            WriteCapacityUnits: '1'
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '1'
