AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for Oscar winner predictions
Resources:
  facebookNewsBotUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '2'
        WriteCapacityUnits: '1'
